server:
  port: 8080
  servlet:
    context-path: /clipped

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clipped
    username: root
    password: password1!
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

example:
  "Hello, from putangina mo test1!"